/* Generated By:JavaCC: Do not edit this line. ExpRegsConstants.java */
package uniandes.teolen.parserJavaCC.newParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpRegsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNION = 5;
  /** RegularExpression Id. */
  int CLOSURE_1 = 6;
  /** RegularExpression Id. */
  int CLOSURE_2 = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int LBRACE = 10;
  /** RegularExpression Id. */
  int RBRACE = 11;
  /** RegularExpression Id. */
  int ASIGNACION = 12;
  /** RegularExpression Id. */
  int DEFINICION = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int SYMBOL = 15;
  /** RegularExpression Id. */
  int ALPHABET = 16;
  /** RegularExpression Id. */
  int ER_NAME = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int LARGE = 19;
  /** RegularExpression Id. */
  int SMALL = 20;
  /** RegularExpression Id. */
  int EMPTY_SET = 22;
  /** RegularExpression Id. */
  int EMPTY_STRING = 23;
  /** RegularExpression Id. */
  int CONSTANT = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"|\"",
    "\"*\"",
    "\"+\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\":\"",
    "\",\"",
    "<SYMBOL>",
    "\"Alphabet\"",
    "<ER_NAME>",
    "<DIGIT>",
    "<LARGE>",
    "<SMALL>",
    "\"= (\"",
    "\"@\"",
    "\"$\"",
    "<CONSTANT>",
  };

}
